<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('profiles')->delete();
        
        \DB::table('profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => NULL,
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-10-28 07:19:45',
                'updated_at' => '2021-10-28 07:19:45',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => NULL,
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-10-28 07:19:45',
                'updated_at' => '2021-10-28 07:19:45',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 3,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => 'EQPDk31xCI.jpeg',
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-10-28 08:50:41',
                'updated_at' => '2021-10-29 13:15:09',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 4,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/ItZvSZefvbXXLaSiYrUBRKBG37okoMl1rNlLzmtn.png',
                'country' => NULL,
                'phone' => '+1 123 456 7890',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => 'yelloman@yahoo.com',
                'created_at' => '2021-10-29 12:27:54',
                'updated_at' => '2022-01-13 12:00:18',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 5,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => 'x4cWWeBjRNpd9pgx5utqAabegGhjolCMaJ3fqYRS.jpeg',
                'country' => NULL,
                'phone' => '0321321235',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-10-29 12:39:11',
                'updated_at' => '2021-10-29 12:39:11',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 6,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => 'mrLPjBPkmE.jpeg',
                'country' => NULL,
                'phone' => '0321321235',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 06:33:28',
                'updated_at' => '2021-11-02 13:06:26',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 7,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/Pv5jwYezwNu3sjrb63pmN0MKzLEbUWVqHCtMEqzO.jpeg',
                'country' => NULL,
                'phone' => '0321321235',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 06:38:23',
                'updated_at' => '2021-11-01 06:38:23',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 8,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/fdzAluwHQjtZlmgAklgxqBZjlcHmgvSMuDtQdajX.jpeg',
                'country' => NULL,
                'phone' => '0333333300',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 06:39:23',
                'updated_at' => '2021-11-01 06:39:23',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 9,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '1999-09-01',
                'pic' => '/O7Wsp7cp2Nw43sh1ZSMXWIjZmin7MyhEeRew0y4o.jpeg',
                'country' => NULL,
                'phone' => '03213212351',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 001،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:02:51',
                'updated_at' => '2021-11-18 05:52:05',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 10,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/IIr7ipRtqdBQ7WTkhA2UGaNcjATgTeBQDFA6JyL7.png',
                'country' => NULL,
                'phone' => '03000033333',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:21:48',
                'updated_at' => '2021-11-01 07:21:48',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 11,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/6HKmJJ3BSFEChVO7Yn3cZGpsJcPW07IHFZ9zv670.png',
                'country' => NULL,
                'phone' => '0321321235',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:23:35',
                'updated_at' => '2021-11-01 07:23:35',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 12,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/fLbfGobhFsjbTR4C8S7d8Tq6maka3HLOq5WlwAY5.jpeg',
                'country' => NULL,
                'phone' => '0321321235',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:26:34',
                'updated_at' => '2021-11-01 07:26:34',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 13,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/kE5EqDQYY67Qoow2Oz31lOBQrm0eSQw3xPYYdvmr.png',
                'country' => NULL,
                'phone' => '123456',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:29:11',
                'updated_at' => '2021-11-01 07:29:11',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 14,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/Mz3PEMEITXAaMPDCvB9JRQKHEfAoVgfheT3NiePO.png',
                'country' => NULL,
                'phone' => '0341313232',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:33:13',
                'updated_at' => '2021-11-01 07:33:13',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 15,
                'bio' => NULL,
                'gender' => 'Male',
                'dob' => '2000-02-16',
                'pic' => '/EVdWlsmu9FCyFDJTYXaMH8rtD1FsVQvw86rAhcIX.png',
                'country' => NULL,
                'phone' => '88888888',
                'state' => NULL,
                'city' => NULL,
                'address' => 'C - 32 / II / I، KDA Scheme No. 01،',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-01 07:34:54',
                'updated_at' => '2021-11-01 07:34:54',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 16,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/Er7vP5IEJb38G0f1y8pm4Kw0qSNOQ3j5YvObs03l.png',
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-12 12:18:15',
                'updated_at' => '2021-11-12 12:18:15',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 17,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/fSGVav7X7cpy9h1YvKiPza2ykcebN8FpIWBa8Jz1.png',
                'country' => NULL,
                'phone' => '123456',
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-15 05:12:27',
                'updated_at' => '2021-11-15 05:12:27',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 18,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/Fxs70vDTaVhOX0jp0vptawHiyakRfgBKPbTnx8Au.png',
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-16 05:54:55',
                'updated_at' => '2021-11-16 05:54:55',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 19,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/dPJwuxrxPJNiFToM0kxZV7iuyWJTfO7ZYawoBpwK.jpeg',
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-18 06:05:24',
                'updated_at' => '2021-11-18 06:05:24',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 20,
                'bio' => NULL,
                'gender' => 'male',
                'dob' => NULL,
                'pic' => '/qmbYmMUs3bikXxgQ7GwImpsQjIOzxRZu13Jo9QvX.jpeg',
                'country' => NULL,
                'phone' => '0341313131',
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => 'yelloman@yahoo.com',
                'created_at' => '2021-11-18 06:30:25',
                'updated_at' => '2021-11-18 09:06:52',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 21,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/aKifGb7BFM4SPGmKMz9TbFGr5GYYZORsz4TKJj4e.jpeg',
                'country' => NULL,
                'phone' => '0321321235',
                'state' => NULL,
                'city' => NULL,
                'address' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-11-18 06:39:26',
                'updated_at' => '2021-11-18 12:55:00',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 22,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/8ux7OaN1CWGsrLZUtjqtl9R6sPj7TI40ThKI5zSX.jpeg',
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-12-03 16:30:00',
                'updated_at' => '2021-12-03 16:30:00',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 23,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/DkVjfcmQHNt4yRm6PmLua0ATiIJgl6TyMjGRuiMo.jpeg',
                'country' => NULL,
                'phone' => '1313131',
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2021-12-03 16:39:06',
                'updated_at' => '2021-12-03 16:39:06',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 24,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/fgok0Zr2jgtZ4Q2SPdA6jkpHtgyRICmbFC74rJiu.jpeg',
                'country' => NULL,
                'phone' => '12121',
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2022-01-17 20:20:03',
                'updated_at' => '2022-01-17 20:20:03',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 25,
                'bio' => NULL,
                'gender' => NULL,
                'dob' => NULL,
                'pic' => '/659ODXCivjOjhEkTYcrJ7XN8w14iGRy5ssoIEIkF.jpeg',
                'country' => NULL,
                'phone' => NULL,
                'state' => NULL,
                'city' => NULL,
                'address' => NULL,
                'postal' => NULL,
                'skype' => NULL,
                'created_at' => '2022-01-17 20:36:32',
                'updated_at' => '2022-01-17 20:36:32',
            ),
        ));
        
        
    }
}