<?php

use Faker\Factory;
use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Role;
use App\Permission;
use App\CommonSetting;


class UsersTableSeeder extends DatabaseSeeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@developer.com',
                'password' => '$2y$10$GB7gTe8V8VM/SnAHMgsx7ujZJJrsJ62HKViUYYrRJbEx29BCtsdHy',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2021-10-28 07:19:45',
                'updated_at' => '2021-10-28 07:19:45',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'User',
                'email' => 'admin@ramzi.com',
                'password' => '$2y$10$F2BYBiCjWSI.ouOronoqQeJjZGQBjHumg1QSAkfj8MORpRQMBe7SW',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2021-10-28 07:19:45',
                'updated_at' => '2021-10-28 07:19:45',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'national',
                'email' => 'national@yopmail.com',
                'password' => '$2y$10$u9L0h1oQl7VGb8xYVXvAZeQX0myooYN5NZS2Dj64CP1HMDMFpqlPi',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-10-28 08:50:41',
                'updated_at' => '2021-10-29 13:15:09',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'zuhi',
                'email' => 'zuhi@yopmail.com',
                'password' => '$2y$10$e136xGbZYoLTOKRvhoAd2uuzGHg7YXy3rQtrwIotaSmiWLumfZkt.',
                'company_id' => 3,
                'department_id' => 1,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => 'fJjzlJ96AwRjmxzpZeX6hsG8qDcInKbAkLRDMUddqIsUFV8OC9wj23iGAbFV',
                'created_at' => '2021-10-29 12:27:54',
                'updated_at' => '2021-11-12 11:28:22',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'imdad ali . qr',
                'email' => 'imdad@truck.com',
                'password' => '$2y$10$Yse/HS2Ck3yjFxtTVjgtN.RHSLgsv.1Qx7.mvDCsy.hwlypY7dT4G',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-10-29 12:39:11',
                'updated_at' => '2021-10-29 12:39:11',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'aftab . ali',
                'email' => 'aftab@yopmail.com',
                'password' => '$2y$10$LBpVA73f/B1OI1Ywi2xOdej3qbjCER8Tj5LEDA4D4nXMZtiYFABay',
                'company_id' => 3,
                'department_id' => 1,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 06:33:28',
                'updated_at' => '2021-11-02 13:06:26',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'waqas',
                'email' => 'waqas@yopmail.com',
                'password' => '$2y$10$Tkspj17XfTTc0Bmd9N2se.CAgwLNAJx7sz4.GBnUQa/iHRWOdAAGG',
                'company_id' => 3,
                'department_id' => 2,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 06:38:23',
                'updated_at' => '2021-11-01 06:38:23',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'rashed',
                'email' => 'rashed@yopmail.com',
                'password' => '$2y$10$Pr1SDokmjCfhLxtsD9oTNu0s9R5SdQ7xD1goapIU4A0oJvuCGa7fO',
                'company_id' => 3,
                'department_id' => 2,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 06:39:23',
                'updated_at' => '2021-11-01 06:39:23',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'sam',
                'email' => 'sam@yopmail.com',
                'password' => '$2y$10$pLq0/7rkoe4ccb7mG1TsW./zg.GQQ7C1z6H5be3byTBXLJ4bcEKwu',
                'company_id' => 3,
                'department_id' => 1,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:02:51',
                'updated_at' => '2021-11-18 05:52:22',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'shareef',
                'email' => 'shareef@yopmail.com',
                'password' => '$2y$10$nvB5mY/MRRvVFW2utwVMnereQvvtw.7YjB0VCsIOgrw4Kg82Lnh9S',
                'company_id' => 3,
                'department_id' => 1,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:21:48',
                'updated_at' => '2021-11-01 07:21:48',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ali',
                'email' => 'zuhi@yahoo.com',
                'password' => '$2y$10$Mvh9.SuqLpN/DFW.L/tPn.zGdhw4W2zX/TiZt2hbO/JtfD9Ahtb1q',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:23:35',
                'updated_at' => '2021-11-01 07:23:35',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'kc',
                'email' => 'ks@yopmail.com',
                'password' => '$2y$10$5lcQx6Da75N7O3LlgMIOxunAflOysRngcITGnLPiXEJJmxjpuZ0uC',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:26:34',
                'updated_at' => '2021-11-01 07:26:34',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'js',
                'email' => 'js@yopmail.com',
                'password' => '$2y$10$WXfR1UxrPBqij6Dp2xy0aORlHiRz7Qv6XEFhenmrqRUltLm3uwBqK',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:29:11',
                'updated_at' => '2021-11-01 07:29:11',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'asif',
                'email' => 'asif@yopmail.com',
                'password' => '$2y$10$dy1vL7dDEOg6d5XiLFeRYOSY6.bPf/RJ80GzU/KmAILSMnKm3PpoW',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:33:13',
                'updated_at' => '2021-11-01 07:33:13',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'walid',
                'email' => 'walid@yopmail.com',
                'password' => '$2y$10$WwS7jfw0sqrVX7O8Cok6behiQ.eqXk4KMbmm863QngECyFVRZPDzu',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-01 07:34:54',
                'updated_at' => '2021-11-01 07:34:54',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'waqas',
                'email' => 'waqas_khalid@yopmail.com',
                'password' => '$2y$10$OyvOdxqdVr6R/2ML/K6PIeHaHVp4SghHkQ6qbPXFMoh85gZPSqJhC',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-12 12:18:15',
                'updated_at' => '2021-11-16 07:31:18',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Zk',
                'email' => 'zk@yopmail.com',
                'password' => '$2y$10$OcPQE1eDl444yWXXBZL7H./RJebP3VJAMHpenkHKoZcY51ry7oIge',
                'company_id' => 3,
                'department_id' => 4,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-15 05:12:27',
                'updated_at' => '2021-11-15 05:12:27',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'jojo',
                'email' => 'jojo@yahoo.com',
                'password' => '$2y$10$Wqdz8pdNMJi5b87u4rvyjO3bzNd0R/A3h9j496J92pjxuhswgj8wy',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 1,
                'remember_token' => NULL,
                'created_at' => '2021-11-16 05:54:55',
                'updated_at' => '2021-11-16 07:31:30',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'oxford grammar',
                'email' => 'oxford@yopmail.com',
                'password' => '$2y$10$BHxdckggKA8MamEa.x693u5HxmJpyq9ih7mwESNcltzyC5Q5W7sAW',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-18 06:05:24',
                'updated_at' => '2021-11-18 06:06:13',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'john',
                'email' => 'john@yopmail.com',
                'password' => '$2y$10$ANPEapDPtMhCPkdUXc/1KOYgk284FNWr4OqS6zFQ73UPYg45tuweO',
                'company_id' => 19,
                'department_id' => 8,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-18 06:30:25',
                'updated_at' => '2021-11-18 09:10:27',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'kashan ali qureshi',
                'email' => 'kashan@yopmail.com',
                'password' => '$2y$10$7zgNwiEouadWTAWUhgCbte3PefnXtLWf4NWtix/3T2qsDfWbCYPK2',
                'company_id' => 19,
                'department_id' => 8,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-11-18 06:39:26',
                'updated_at' => '2021-11-18 06:39:26',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Tafsol',
                'email' => 'tafsol@yopmail.com',
                'password' => '$2y$10$emc1oFt0JQh8t0sSSLIMW.tn/T/D1nb.XPENBvS7EgIo2ErpcsJHm',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-12-03 16:30:00',
                'updated_at' => '2021-12-03 16:31:22',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Muhammad',
                'email' => 'mct@tafsol.com',
                'password' => '$2y$10$er3FDBuwG.yNr60agPkH6.XjnTd1BRvX0lTkt3Cj/y.O1TfTZaYdO',
                'company_id' => 22,
                'department_id' => 9,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2021-12-03 16:39:06',
                'updated_at' => '2021-12-03 16:39:06',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Ramzi',
                'email' => 'ramzi123@mail.com',
                'password' => '$2y$10$v7Vfd0YjgvKgucOnhJZDPesbaqelL5BlIotmHy8Hrw8VwEmJ0yYdm',
                'company_id' => 3,
                'department_id' => 1,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2022-01-17 20:20:03',
                'updated_at' => '2022-01-17 20:20:03',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Samosa',
                'email' => 'samosa@yopmail.com',
                'password' => '$2y$10$OE9mw.TgL6zAvC9fYIty2u5DiNQaC5sXjFxEbGpcoRT8xs7oD3jIW',
                'company_id' => NULL,
                'department_id' => NULL,
                'provider_id' => NULL,
                'provider' => NULL,
                'status' => 0,
                'remember_token' => NULL,
                'created_at' => '2022-01-17 20:36:32',
                'updated_at' => '2022-01-17 20:36:59',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}